# Development Configuration
app:
  name: "EchoTales-Enhanced"
  version: "2.0.0"
  environment: "development"
  debug: true
  host: "localhost"
  port: 5000

database:
  type: "sqlite"
  url: "sqlite:///data/cache/echotales_dev.db"
  echo: true

redis:
  host: "localhost"
  port: 6379
  db: 0
  decode_responses: true

processing:
  booknlp:
    models_path: "models/booknlp/"
    batch_size: 32
    max_workers: 4
  
  character_analysis:
    personality_model: "bert-base-uncased"
    emotion_model: "j-hartmann/emotion-english-distilroberta-base"
    physical_description_model: "microsoft/DialoGPT-medium"
    
  scene_analysis:
    setting_classifier: "facebook/bart-large-mnli"
    transition_detector: "sentence-transformers/all-MiniLM-L6-v2"

voice_dataset:
  path: "data/voice_dataset/"
  male_actors: 12
  female_actors: 12
  samples_per_actor: 44
  supported_formats: ["wav", "mp3", "flac"]
  
  classification:
    features: ["pitch", "tempo", "timbre", "emotion", "age_group"]
    similarity_threshold: 0.8
    
  processing:
    sample_rate: 22050
    duration_range: [2, 10]  # seconds
    noise_reduction: true

tts:
  default_engine: "openvoice"
  engines:
    openvoice:
      model_path: "models/tts/openvoice/"
      device: "cuda"
      quality: "high"
    elevenlabs:
      api_key: "${ELEVENLABS_API_KEY}"
      voice_stability: 0.5
      voice_similarity: 0.5
    edge:
      language: "en-US"
      rate: "+0%"
      pitch: "+0Hz"
    bark:
      model_path: "models/tts/bark/"
      device: "cuda"

audio:
  output_format: "mp3"
  sample_rate: 22050
  bitrate: "192k"
  quality: "high"
  effects:
    normalize: true
    fade_in: 0.1
    fade_out: 0.2
    silence_threshold: -50

image_generation:
  # Output directory for generated images
  output_directory: "data/output/images"
  
  # Default settings
  default_provider: "auto"  # Auto-select best available provider
  default_style: "photorealistic"
  default_size: "1024x1024"
  default_quality: "standard"
  
  # API Provider Settings (ordered by preference - free first)
  providers:
    # Google Gemini (Free tier - best option for prompt enhancement)
    gemini:
      enabled: true
      api_key: "${GEMINI_API_KEY}"
      max_requests_per_minute: 15
      free_tier: true
      priority: 1  # Highest priority
      features:
        - "prompt_enhancement"
        - "text_to_image_via_fallback"
      
    # HuggingFace (Free tier available)
    huggingface:
      enabled: true
      api_key: "${HUGGINGFACE_API_KEY}"
      max_requests_per_minute: 10
      free_tier: true
      priority: 2
      model: "stabilityai/stable-diffusion-xl-base-1.0"
      alternative_models:
        - "runwayml/stable-diffusion-v1-5"
        - "CompVis/stable-diffusion-v1-4"
      features:
        - "text_to_image"
        - "negative_prompts"
        - "custom_parameters"
      
    # OpenAI DALL-E (Limited use - high quality)
    openai:
      enabled: true
      api_key: "${OPENAI_API_KEY}"
      max_requests_per_minute: 5
      free_tier: false
      priority: 3
      model: "dall-e-3"
      fallback_model: "dall-e-2"
      features:
        - "text_to_image"
        - "high_quality"
        - "prompt_revision"
      
    # Stability AI (Paid but excellent quality)
    stability:
      enabled: false  # Disabled by default due to cost
      api_key: "${STABILITY_API_KEY}"
      engine_id: "stable-diffusion-xl-1024-v1-0"
      max_requests_per_minute: 20
      free_tier: false
      priority: 4
      features:
        - "text_to_image"
        - "advanced_parameters"
        - "multiple_models"
  
  # Style presets for different image types
  style_presets:
    character_portraits:
      style: "portrait"
      size: "1024x1024"
      prefix: "professional portrait, detailed facial features, studio lighting,"
      suffix: "masterpiece, best quality, highly detailed"
      
    scene_backgrounds:
      style: "cinematic"
      size: "1024x1024"
      prefix: "cinematic shot, dramatic lighting, movie still, high production value,"
      suffix: "masterpiece, best quality, highly detailed, wide angle"
      
    book_covers:
      style: "artistic"
      size: "1024x1536"
      prefix: "professional book cover design, artistic rendering, typography space,"
      suffix: "masterpiece, best quality, highly detailed, marketing quality"
      
    fantasy_art:
      style: "fantasy"
      size: "1024x1024"
      prefix: "fantasy art, magical atmosphere, detailed fantasy illustration,"
      suffix: "masterpiece, best quality, highly detailed, fantasy style"

caching:
  enabled: true
  ttl: 3600  # seconds
  storage: "redis"
  keys:
    novels: "novel:{book_id}"
    characters: "characters:{book_id}"
    audio: "audio:{book_id}:{chapter}"
    images: "images:{book_id}:{character_id}"

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/development.log"
  max_size: "10MB"
  backup_count: 5